### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by asli-ural** [EFEKAANLULE/jotform-todo#4]
https://github.com/EFEKAANLULE/jotform-todo/blob/8d1ac4d2c44312f64fa74ae0f36c793b38c32bb7/src/MyApp.js#L21
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
```
const asli =[1,2,3,4,5]

const [val, val2, val3, ...values] = asli;

```

please use this operator for getting array's values

**Comment by EFEKAANLULE** [comment]
Change this :
        const tasks = submissions.map((submission, index) => {
        const answers = submission.answers || [];
        const name = (answers[1] && answers[1].answer) || '';
        const description = (answers[2] && answers[2].answer) || '';
        return { id: index, name, description };
        
        
        To this :
  const tasks = submissions.map((submission, index) => {
  const { answers } = submission;
  const name = (answers[1]?.answer) || '';
  const description = (answers[2]?.answer) || '';
  return { id: index, ...answers, name, description };
});



But i am not sure if spread operator is necessarry in this app. I did not understand this part fully
